### ISSUE TITLE
Fix umbrella sampling

### ISSUE THREAD

**Issue by kyleabeauchamp** [choderalab/pymbar-examples#15]
Currently relies on `mbar.indices` but this variable was removed in the switch to N_k

**Comment by mrshirts** [comment]
I'll take a look at this today.

**Comment by mrshirts** [comment]
Some other issues: 
- heat_capacity.py
Some issues with observable shaping.
- parallel-tempering-2dpmf.py
 uses computePMF_states, and assumes 2D bincounts

I'll get to these by tonight.

**Comment by mrshirts** [comment]
Ah, the umbrella-sampling.py problem was part of the kl-divergence code.  I'll take that out for now.  It should go in when we do the PMF code update.

**Comment by mrshirts** [comment]
OK, updated that code with https://github.com/choderalab/pymbar-examples/pull/16

**Comment by kyleabeauchamp** [comment]
Looks fixed
